### ISSUE TITLE
64-bit addresses is a terrible idea

### ISSUE THREAD

**Issue by iitalics** [treyzania/bollocksvm#1]
Writing a 64-bit-address page table sucks, also at this point we can't even
1) create 64-bit immediate values without like 16 total instructions
2) load 64-bit words without even more instructions than that

**Comment by treyzania** [comment]
>16 total instructions

This is why I'm a fan of having variable-length instructions.  We'd need to have multiple literal load instructions, but if we don't care about how wide instructions are then that shouldn't be an issue anyways.  Also it would make using `\n` as a NOP less unfun to deal with and allow us to use `#` as our "disable execution" instruction that reenableas at `\n`.

>64-bit words

Again, with variable-width instructions this would be easier.

**Comment by iitalics** [comment]
OK, but now how do we deal with relative jumps? Do you specify a byte offset?

**Comment by treyzania** [comment]
I guess we'd have to do that and hope people are smart enough to keep track of their data.
